name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo ✨
        uses: actions/checkout@v2

      - name: Check formatting 🧼
        run: cargo fmt -- --check

      - name: Lint 🛑
        run: cargo clippy -- -D warnings

      - name: Build 🧱
        run: cargo build --verbose
